version: '3.8'
services:
  postgres:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: shekina
      POSTGRES_PASSWORD: shekina_pass
      POSTGRES_DB: shekina_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
  rips_validator:
    build: ./docker/rips_validator
    depends_on:
      - postgres
    ports:
      - "8080:8080"
volumes:
  pgdata:
